{% set version = "6.3.0" %}
{% set datumgrid_ver = "1.8" %}

package:
  name: proj
  version: {{ version }}

source:
  - url: http://download.osgeo.org/proj/proj-{{ version }}.tar.gz
    sha256: 68ce9ba0005d442c2c1d238a3b9bc6654c358159b4af467b91e8d5b407c79c77
  - url: http://download.osgeo.org/proj/proj-datumgrid-{{ datumgrid_ver }}.tar.gz
    sha256: 3ff6618a0acc9f0b9b4f6a62e7ff0f7bf538fb4f74de47ad04da1317408fcc15
    folder: data

build:
  number: 0
  skip: True  # [win and vc<14]
  run_exports:
    # so name changes in bugfix revisions.  Pin to bugfix revision.
    #    https://abi-laboratory.pro/tracker/timeline/proj/
    - {{ pin_subpackage('proj', max_pin='x.x.x') }}

requirements:
  build:
    - cmake  # [win]
    - pkg-config  # [not win]
    - make  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - sqlite
  run:
    - sqlite
  run_constrained:
    - proj4 ==999999999999

test:
  commands:
    # Check if NAD27/NAD83 datum shifting is present if `conus` is present.
    - test -f $PREFIX/share/proj/conus  # [not win]
    - if not exist %LIBRARY_PREFIX%\\share\\proj\\conus exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\proj.lib exit 1  # [win]
    - echo -105 40 | proj +proj=utm +zone=13 +ellps=WGS84
    - echo -117 30 | cs2cs +proj=latlong +datum=NAD27 +to +proj=latlong +datum=NAD83
    - echo -105 40 | cs2cs +init=epsg:4326 +to +init=epsg:2975

about:
  home: https://proj.org/
  license: MIT
  license_file: COPYING
  summary: 'Cartographic Projections and Coordinate Transformations Library'

extra:
  recipe-maintainers:
    - ocefpaf
    - pelson
    - msarahan
    - xylar
    - snowman2
