travis:
  secure:
    BINSTAR_TOKEN: j5yKMW88rlzBXWTsUneuYjhQctVi3jWK6Oe+NUWSZRuMKX1ayk36d/jxUP1cZPt/CDvlnK7EFWzYQgRcg4/iNgej7lT/1HhHVgoREgjtaM9ot5SJQzxu1j68g5CD1Zj1ZOMKfU89ddb9GwBYq/VPddijhb9VCpk4jLRikvAXxP9kXyjSFep/CjpF3JHvLrBgLwTWQO7jF99G8quS8JoG7AishGqmBugexFo4A/ldqJRNhA22uSEqRbIQj3Npz9OUNutdbDIUjppoNHMcjN25jntGSMotEZAYbgqcXVeVxU/Y94bdlMBoXqx9/WCtFRHmk/EvNsZOOsxIYGCedkrCcqVXrKwkrDP3ot8VkpOb2KmVO2KjpUFNvxMLY2QA335SzuRkx6VwEE7Wds45oMnTbAEKquM6U0fi779BhVwruuEw0ZsEyuchndSwoLA5yVg4G0kEFKKnwvEj1DkOHivDi4I/r7IShJJu6H6udtr2yfqQS5kKK6P2wYOPhboSDgGFA36m//97d1tVtCqAJgIln3uQmVi1qGfk1rBQOlNDObT9HxEYN54Xzd4+pbb3zuWR2BUyQ46X9Yjr+aAUrku9Uqu+0U+T/0jbcufeVyH/xWK1SDjZBnkH0r6VWrSx9jjt9U5BGMxtaOEHNBg7GS3G9Hs1rGDQ5TBWLY5lPphcS+Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
