travis:
  secure:
    BINSTAR_TOKEN: jBIgBv1fWxJUIvGbDz5q6BiaSOhmZGUVnG4PNzY11f3X4GIrTDDFMdRhC15JmdovCopVPDaWC4VouTNQ4X+RBYUJJbLKzUGjIax8h50lFpRor2MtuS7oOtQQrMKOceLqTBKkxVPigLIGwJiI7KF0h0HooBX1QjPfryZPwZVb3IDvVWuUFU3XiiFSypY+/V5NtdyaYseaeGfqAizEh4Ldvj37mvQfIybSrguKv1cyngAPabIcPzUCDu1ryHdjeNZT/FggpJ8V3MKg6kBpc0IaOs06mjXLV7QOaOqPwia8EkANp2xM634U59yqjohvGTaxRDKZMyd/U1LuZVr0mZch/MXxxH8CwUoD+MFCzu5ZWPnia3M9gOyaPvWpSki2ehc4k3In2PAOKEen6A/sECM3Cx+0a1ExaJLCAVgoQl/kUmOQN7eA9Ezmhuiw7/Ab/13qdTH5mUQutPHdmDpbeQ7kOKmE5pBFL13on47J4z83bcUeotI2OuZisE5BKIaviD0NhX8bZQcv3hYv/Q4+Ge+EwGvs8JBIl00wppujQVdnEYXFw/NYvjUOPhf+NfrwbTmjAV+AA4k8B/Pt5cSLXO1J3fpuCPFKxnXe6E/fts6nV80pfuu926AsWaPC0zAQq79StYJWSErO7rBgki3t35J/1hV8A9hBrasGAYTn0Ed6LaE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
